defaults:
  - base
  - model: eegpt
  - training: base
  -  _self_

# Data configuration
data:
  batch_size: 32
  num_workers: 1
  datasets: 
    workload: 'finetune'

# Dataset used for finetuning
finetune_datasets:
  workload: 'finetune'

# Training configuration
model_type: 'eegpt'
multitask: false
master_port: 51002


