defaults:
  - base
  - models: eegpt
  - training: full_finetune
  - platform: bwuni_dev
  - _self_

# Enable Hydra multirun for sweeping
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      dropout_rate: 0.3 #, 0.1 #, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0
      seed: 1 # 2 #, 3, 4, 5, 6, 7, 8, 9, 10

# Experiment name
name: exp_1_eegpt_workload_random_dropout_sweep

# Training configuration
model_type: 'eegpt'
multitask: false
master_port: 51002

# Seed parameter
seed: 1

# Dropout parameters (swept by Hydra)
random_dropout: true
dropout_rate: 0.1  # Will be overridden by Hydra sweep
dropout_seed: ${seed}

# Data configuration
data:
  batch_size: 32
  num_workers: 1
  datasets:
    workload: 'finetune'
  random_dropout: ${random_dropout}
  dropout_rate: ${dropout_rate}
  dropout_seed: ${dropout_seed}

# Logging configuration
logging:
  experiment_name: ${name}_dropout_${dropout_rate}_seed_${seed}
  output_dir: ./outputs/${name}/full_finetune/random_dropout/${dropout_rate}/seed_${seed}
  ckpt_dir: ./checkpoints/${name}/full_finetune/random_dropout/${dropout_rate}/seed_${seed}

  tags:
    - eegpt
    - workload
    - random_dropout_sweep
    - dropout_${dropout_rate}