# @package _global_

hydra:
  run:
    dir: ./outputs/preproc/${now:%Y-%m-%d}/${now:%H-%M-%S}/${name}
  sweep:
    dir: ./outputs/preproc/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${name}/seed_${seed}